# ASSIGNMENT NO 3

In [1]:
import numpy as np

# creating a array using numpy arange
array = np.arange(2, 50, 3)

print(array)


[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [2]:
import numpy as np

# creating empty list:
lst_1 = []
lst_2 = []

for i in range(5):
  x=int(input("\nEnter the value for lst_1 : "))
  lst_1.append(x)

for i in range(5):
  x=int(input("\nEnter the value for lst_2 : "))
  lst_2.append(x)

arr_1 = np.array(lst_1)
arr_2 = np.array(lst_2)

# concatenating:
arr = np.concatenate((arr_1, arr_2))
print("\nArray value for concatenated arr :",arr)

# sorting: 
sortArr = np.sort(arr)
print("\nSorted Array for concatenated arr :",sortArr)


Enter the value for lst_1 : 2

Enter the value for lst_1 : 2

Enter the value for lst_1 : 5

Enter the value for lst_1 : 1

Enter the value for lst_1 : 3

Enter the value for lst_2 : 4

Enter the value for lst_2 : 5

Enter the value for lst_2 : 8

Enter the value for lst_2 : 7

Enter the value for lst_2 : 9

Array value for concatenated arr : [2 2 5 1 3 4 5 8 7 9]

Sorted Array for concatenated arr : [1 2 2 3 4 5 5 7 8 9]


In [4]:
import numpy as np

# creating a 2D array
arr = np.array([[2,4,6],[1,3,5]])

# Printing array dimensions 
print("\nDimensions in array : ", arr.ndim)     #snippet for finding dimension: ArrayName.ndim
 
# Printing array size
print("\nSize of array : ", arr.size)           #snippet for finding size: ArrayName.size


Dimensions in array :  2

Size of array :  6


In [5]:
import numpy as np

# creating 1D array

arr = np.arange(10)
print("\nShape of Array :",arr.shape)

# converting using newaxis in row wise

row_arr = arr[np.newaxis, :]
print("\nShape of 2d Array in row major :",row_arr.shape)

# converting using newaxis in column wise

col_arr = arr[:, np.newaxis]
print("\nShape of 2d Array in column major :",col_arr.shape)


Shape of Array : (10,)

Shape of 2d Array in row major : (1, 10)

Shape of 2d Array in column major : (10, 1)


In [8]:
import numpy as np

# creating a array with square values

arr_1 = np.square([1, 2, 3, 4])
arr_2 = np.square([6, 7, 8, 9])

# stack and print

print("\nHorizontal Append :", np.hstack((arr_1, arr_2)))
print("\nVertical Append :", np.vstack((arr_1, arr_2)))


Horizontal Append : [ 1  4  9 16 36 49 64 81]

Vertical Append : [[ 1  4  9 16]
 [36 49 64 81]]


In [11]:
import numpy as np

# creating a array 
array_1 = np.array([1, 4, 9, 16, 25, 1, 4, 2, 3, 2, 5, 6, 5, 7, 8, 10])

# getting unique charater and its count
unique, counts = np.unique(array_1, return_counts=True)

array = np.asarray((unique, counts)).T

print(array)

[[ 1  2]
 [ 2  2]
 [ 3  1]
 [ 4  2]
 [ 5  2]
 [ 6  1]
 [ 7  1]
 [ 8  1]
 [ 9  1]
 [10  1]
 [16  1]
 [25  1]]
